# Generated by Django 4.2.5 on 2023-11-14 22:50

import datetime
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0002_supply_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="log",
            options={"verbose_name": "Лог", "verbose_name_plural": "Логи"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AlterModelOptions(
            name="sale",
            options={"verbose_name": "Продажа", "verbose_name_plural": "Продажи"},
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"verbose_name": "Поставщик", "verbose_name_plural": "Поставщики"},
        ),
        migrations.AlterModelOptions(
            name="supply",
            options={"verbose_name": "Поставка", "verbose_name_plural": "Поставки"},
        ),
        migrations.RemoveField(
            model_name="product",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="supply",
            name="deleted",
        ),
        migrations.AlterField(
            model_name="log",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано в"),
        ),
        migrations.AlterField(
            model_name="log",
            name="data",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                verbose_name="Данные",
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено в"),
        ),
        migrations.AlterField(
            model_name="product",
            name="count",
            field=models.IntegerField(verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="product",
            name="receipt_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Дата поставки"
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="count",
            field=models.IntegerField(verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="sale",
            name="date",
            field=models.DateField(verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="sale",
            name="product",
            field=models.ForeignKey(
                db_column="product_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="labs.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="retail_price",
            field=models.FloatField(verbose_name="Розничная цена"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(max_length=255, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="who_to_contact",
            field=models.CharField(
                db_column="", max_length=255, verbose_name="К кому обращаться"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="count",
            field=models.IntegerField(default=0, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="supply",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True, editable=False, verbose_name="Создано в"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="product",
            field=models.ForeignKey(
                db_column="product_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="labs.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="supplier",
            field=models.ForeignKey(
                db_column="supplier_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="labs.supplier",
                verbose_name="Поставщик",
            ),
        ),
    ]
