# Generated by Django 4.2.5 on 2023-11-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0003_alter_log_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
            ],
        ),
    ]
