# Generated by Django 4.2.5 on 2023-11-25 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0005_migration_example"),
    ]

    operations = [
        migrations.AddField(
            model_name="testmodel",
            name="meta_description",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=255,
                verbose_name="Meta description",
            ),
            preserve_default=False,
        ),
    ]
