# Generated by Django 4.2.5 on 2023-11-25 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0006_testmodel_meta_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testmodel",
            name="meta_description",
        ),
    ]
